export const SELECTED_TAB='tabview/selectedTab'
export const CLOSE_TAB='tabview/closeTab'
export const ADD_TAB='tabview/addTab'
export const HOME_TAB='tabview/homeTab'
export const DIY_CLOSE_TAB='tabview/diyCloseTab'